---
- hosts: all
  tasks:

# Formatting and mounting storage
  - name: create partitions for vdb and vdc
    parted:
      device: "{{ item }}"
      number: 1
      state: present
    loop:
      - /dev/vdb
      - /dev/vdc
  - name: format vdb and vdc
    filesystem:
      fstype: ext4
      dev: "{{ item }}"
    loop:
      - /dev/vdb
      - /dev/vdc
  - name: mount vdb to /data1 and vdc to /data2
    mount:
      fstype: ext4
      src: "{{ item.dev }}"
      path: "{{ item.path }}"
      state: mounted
    loop:
      - { dev: '/dev/vdb', path: '/data1' }
      - { dev: '/dev/vdc', path: '/data2' }

# Update hosts file and install Java
  - name: copy hosts files
    synchronize:
      src: /home/training/kafka-ansible/single-playbook/files/etc/hosts
      dest: /etc
  - name: ensure jdk 1.8
    yum:
      name: java-1.8.0-openjdk-devel
      state: present
