---
- hosts: all
  vars:
    BASE_DIRECTORY: /home/training/kafka-ansible/single-playbook
  tasks:

# Formatting and mounting storage
  - name: create partitions for vdb and vdc
    parted:
      device: "{{ item }}"
      number: 1
      state: present
    loop:
      - /dev/vdb
      - /dev/vdc
  - name: format vdb and vdc
    filesystem:
      fstype: ext4
      dev: "{{ item }}"
    loop:
      - /dev/vdb
      - /dev/vdc
  - name: mount vdb to /data1 and vdc to /data2
    mount:
      fstype: ext4
      src: "{{ item.dev }}"
      path: "{{ item.path }}"
      state: mounted
    loop:
      - { dev: '/dev/vdb', path: '/data1' }
      - { dev: '/dev/vdc', path: '/data2' }

# Update hosts file and install Java
  - name: copy hosts files
    synchronize:
      src: "{{ BASE_DIRECTORY }}/files/etc/hosts"
      dest: /etc
  - name: ensure jdk 1.8
    yum:
      name: java-1.8.0-openjdk-devel
      state: present

# Setup zookeeper on zookeeper ensemble
- hosts: ensemble
  vars:
    ZOOKEEPER_VERSION: 3.4.12
  tasks:
  - name: Add user zookeeper
    user:
      name: zookeeper
  - name: Download and Unarchive Zookeeper
    unarchive:
      src: http://www-us.apache.org/dist/zookeeper/zookeeper-{{ ZOOKEEPER_VERSION }}/zookeeper-{{ ZOOKEEPER_VERSION }}.tar.gz
      dest: /opt
      remote_src: yes
      owner: zookeeper
      group: zookeeper
      mode: 0755
  - name: create softlink for zookeeper base dir
    file:
      src: /opt/zookeeper-{{ ZOOKEEPER_VERSION }}
      path: /opt/zookeeper
      state: link
      owner: zookeeper
      group: zookeeper
  - name: Create data directory
    file:
      path: "{{ item }}"
      state: directory
      owner: zookeeper
      group: zookeeper
      mode: 0755
    loop:
      - /data1/zookeeper
      - /var/log/zookeeper

# Setup kafka brokers
- hosts: brokers
  vars:
    SCALA_VERSION: 2.11
    KAFKA_VERSION: 2.0.0
  tasks:
  - name: Add user kafka
    user:
      name: kafka
  - name: Download Kafka Tar
    unarchive:
      src: http://www-us.apache.org/dist/kafka/{{ KAFKA_VERSION }}/kafka_{{ SCALA_VERSION }}-{{ KAFKA_VERSION }}.tgz
      dest: /opt
      remote_src: yes
      owner: kafka
      group: kafka
      mode: 0755
  - name: create softlink for kafka base dir
    file:
      src: /opt/kafka_{{ SCALA_VERSION }}-{{ KAFKA_VERSION }}
      path: /opt/kafka
      state: link
      owner: kafka
      group: kafka
  - name: create directories for kafka data with owner as kafka
    file:
      path: "{{ item }}"
      owner: kafka
      group: kafka
      state: directory
      mode: 0755
    loop:
      - /data1/kafka-logs
      - /data2/kafka-logs

# Setup kafka client
- hosts: gateways
  vars:
    SCALA_VERSION: 2.11
    KAFKA_VERSION: 2.0.0
  tasks:
  - name: Add user kafka
    user:
      name: kafka
  - name: Download Kafka Tar
    unarchive:
      src: http://www-us.apache.org/dist/kafka/{{ KAFKA_VERSION }}/kafka_{{ SCALA_VERSION }}-{{ KAFKA_VERSION }}.tgz
      dest: /opt
      remote_src: yes
      owner: kafka
      group: kafka
      mode: 0755
  - name: create softlink for kafka base dir
    file:
      src: /opt/kafka_{{ SCALA_VERSION }}-{{ KAFKA_VERSION }}
      path: /opt/kafka
      state: link
      owner: kafka
      group: kafka
